export const AFFIRMATIONS = [
  'I am filled with light and energy.',
  'I am worthy of happiness and peace.',
  'I attract positivity and joy into my life.',
  'My energy flows effortlessly through everything I do.',
  'I radiate love, warmth, and positivity.',
  'I embrace each moment with a clear mind and an open heart.',
  'I am grateful for all the energy within me.',
  'My mind, body, and spirit are in perfect harmony.',
  'I am a beacon of peace and happiness.',
  'I see endless possibilities all around me.',
  'My energy inspires those around me.',
  'I am surrounded by love and light.',
  'I bring joy and positivity wherever I go.',
  'I let go of any stress and welcome calm energy.',
  'My body is healthy, my mind is clear, and my spirit is energized.',
  'I am proud of the person I am becoming.',
  'I have the power to create positive change.',
  'My potential is limitless.',
  'I am a magnet for abundance and joy.',
  'I focus on what truly matters to me.',
  'Each day, I am growing and evolving.',
  'I am grateful for each breath I take.',
  'I am open to new experiences and possibilities.',
  'I deserve to feel vibrant and alive.',
  'I trust my inner strength and resilience.',
  'My dreams are within my reach.',
  'I choose to live fully and deeply.',
  'I am surrounded by beauty and wonder.',
  'My heart is open to joy and gratitude.',
  'I release what I cannot control.',
  'I am confident in my abilities.',
  'I bring positive energy to everything I do.',
  'I trust the journey I am on.',
  'My spirit is free and full of joy.',
  'I am resilient and capable of overcoming challenges.',
  'I am grateful for the love I give and receive.',
  'I choose to focus on the good in every situation.',
  'I am empowered by my creativity and passion.',
  'I am in tune with my inner wisdom.',
  'I am always learning and growing.',
  'I am at peace with where I am in life.',
  'I choose happiness and positivity.',
  'I am worthy of respect and kindness.',
  'I let go of all that no longer serves me.',
  'I am grateful for the present moment.',
  'I am grounded, calm, and centered.',
  'I am open to the abundance around me.',
  'I am capable of achieving greatness.',
  'I choose to see beauty in every day.',
  'I am thankful for my health and well-being.',
  'My mind is clear, focused, and energized.',
  'I am deserving of all good things.',
  'I radiate peace and tranquility.',
  'I am proud of my accomplishments.',
  'I am always moving forward with courage.',
  'I am loved and appreciated.',
  'My life is filled with positivity and peace.',
  'I am grateful for the lessons each day brings.',
  'I believe in my dreams and goals.',
  'I am a creator of my own happiness.',
  'I am patient, calm, and at ease.',
  'I am enough just as I am.',
  'I trust the timing of my life.',
  'I am grateful for every opportunity to grow.',
  'I attract positive, supportive people into my life.',
  'My heart is filled with gratitude and joy.',
  'I am free from fear and doubt.',
  'I am in harmony with the universe.',
  'My energy is vibrant and uplifting.',
  'I am connected to all that is good.',
  'I am open to love, joy, and peace.',
  'I am grateful for the journey of life.',
  'My inner light shines bright.',
  'I am filled with hope and purpose.',
  'I am mindful of each precious moment.',
  'I deserve love, respect, and happiness.',
  'I welcome all that brings me growth and learning.',
  'I am calm, relaxed, and in control.',
  'My mind is filled with positive thoughts.',
  'I am aligned with my highest good.',
  'I am proud of the person I am becoming.',
  'I trust my intuition and inner wisdom.',
  'I am grateful for the gift of today.',
  'I am worthy of all the love I receive.',
  'I am exactly where I need to be.',
  'I bring joy and laughter into my life.',
  'I let go of stress and embrace calm.',
  'I am grateful for all the beauty in my life.',
  'I am constantly learning and growing.',
  'I choose peace over worry.',
  'I am connected to my inner strength.',
  'I am a vessel of love and compassion.',
  'I am ready to receive all the good coming my way.',
  'My spirit is calm and my mind is clear.',
  'I am patient with myself and others.',
  'I am worthy of my dreams and goals.',
  'I am grateful for each new experience.',
  'I am surrounded by love and positivity.',
  'I am proud of my journey and how far I’ve come.',
  'I am radiant, beautiful, and strong.',
];
