export const creativeActivities = [
  'Write a Poem – Express your feelings creatively in a short, poetic form.',
  'Create a Vision Board – Collect images that inspire your future and create a board to keep you motivated.',
  "Start a Gratitude Jar – Write one thing you're grateful for every day and place it in a jar. Reflect on it later.",
  'Make a Time Capsule – Write a letter to your future self and seal it in an envelope to open a year from now.',
  'Explore a New Hobby – Try drawing, knitting, photography, or anything that sparks your curiosity.',
  'Brainstorm Your Dream Life – Create a mind map of your ideal life, including goals and passions.',
  'Start a Creative Journal – Draw, write, or collage your thoughts and ideas each day.',
  'Plan a Mini Staycation – Design your perfect home getaway, complete with activities you love.',
  'Write a Short Story – Tap into your imagination and write a 500-word story based on a random prompt.',
  'Create a New Recipe – Experiment with ingredients to create a unique dish or drink.',
  'Plant Something – Start a small plant or herb garden and watch it grow.',
  'Start a Daily Sketchbook – Draw something new every day, even if it’s just for 5 minutes.',
  'Invent a New Word – Create a word and define it, then use it throughout your day.',
  'Organize a Themed Dinner Party – Plan a meal around a theme and invite friends or family to join you.',
  'Start a Daily Photography Challenge – Capture one photo a day of something that inspires or interests you.',
  'Make a Self-Care Ritual – Create a personal daily ritual to relax, whether it’s a bath, meditation, or journaling.',
  'Learn Calligraphy or Hand Lettering – Try practicing beautiful handwriting to create greeting cards or artwork.',
  'Create a Daily Playlist – Curate a playlist that matches the energy of your day and listen to it throughout.',
  'Declutter with a Purpose – Go through a drawer or closet and donate things you no longer use.',
  'Write a Letter to Your Future Self – Imagine what you’ll want to tell yourself in 5 years and write it down today.',
  "Start a Podcast or Blog – Share your thoughts, ideas, or experiences on a topic you're passionate about.",
  'Record a Video Journal – Capture your thoughts and reflections in a short video diary.',
  'Try a New Art Medium – Experiment with watercolor, oil pastels, or digital art to express your creativity.',
  'Make a Manifestation List – Write down your desires and visualize them coming true as if they already have.',
  'Create a DIY Craft – Try your hand at crafting something beautiful, like a candle, piece of jewelry, or wall art.',
  'Design Your Dream Home – Draw out the layout and style of your perfect living space.',
  'Redesign Your Workspace – Add personal touches to your workspace to make it more inspiring and productive.',
  'Try Journaling with Prompts – Use writing prompts to dig deeper into your emotions or ideas.',
  'Do a Random Act of Kindness – Give a compliment, buy a coffee for someone, or share a small gift to brighten their day.',
  'Map Your Goals for the Year – Break down your big goals into smaller, manageable tasks and create a timeline.',
  'Create a Personalized Calendar – Design a calendar that inspires you with quotes, pictures, or motivational reminders.',
  'Practice Mindful Listening – Spend the day truly listening to those around you, engaging with empathy and focus.',
  'Learn to Play a New Instrument – Start learning a musical instrument or take it up again if you already know one.',
  'Write a Thank-You Note – Express gratitude with a heartfelt note to someone you appreciate.',
  'Start a Daily Positivity Challenge – Commit to writing down one positive thought every day for a month.',
  'Create a Daily Challenge for Yourself – Challenge yourself to do something new every day, like learning a new word or skill.',
  'Make a Personal Manifesto – Write out a list of values, beliefs, and goals to guide you through life.',
  'Host a Creative Zoom Meetup – Gather a group of creative individuals and share projects or brainstorm together.',
  'Build a Dream Board on Pinterest – Create an online board for the lifestyle, work, and life goals you aspire to.',
  'Watch a Documentary on a New Topic – Expand your knowledge by learning about something you’ve never explored.',
  'Try a Digital Detox Day – Unplug from all screens for a day and spend time in nature, reading, or connecting with people.',
  'Create a Vision Board for Your Future Career – Define your dream job and make a visual representation of it.',
  'Rearrange Your Furniture – Freshen up your living space by changing things around for a new perspective.',
  'Record a Voice Memo to Yourself – Share your thoughts, dreams, and affirmations through a voice recording.',
  'Invent a New Tradition – Start a personal or family tradition that brings joy and togetherness.',
  'Paint or Draw Your Emotions – Express how you’re feeling with color and abstract shapes.',
  'Volunteer Your Time – Spend part of your day helping others or giving back to your community.',
  'Practice Visualization – Spend 10 minutes visualizing your dreams and see yourself achieving them.',
  'Create a DIY Gift for Someone – Make something handmade to give to a friend or loved one.',
  'Host a Virtual Movie Night – Pick a theme and invite friends to watch and discuss films together.',
];
