export const energyBoostIdeas = [
  'Take a 5-Minute Breathing Break – Close your eyes, take deep breaths, and focus on the present moment. Feel the tension melt away.',
  'Step Outside for Fresh Air – A quick walk or a few minutes of fresh air can reset your energy and boost your mood.',
  'Morning Sunshine – Find a sunny spot and soak up the natural light. Let it energize you for the day ahead.',
  'Drink a Glass of Water – Hydrate your body to refresh and energize yourself from the inside out.',
  'Smile at Yourself – Look in the mirror and smile. It’s a simple way to uplift your mood and start your day with positivity.',
  'Gratitude Pause – Take a moment to think of three things you’re grateful for today.',
  'Move Your Body – Stand up and stretch, or do a quick workout to get your blood flowing and raise your energy levels.',
  "Positive Affirmation – Repeat an affirmation like, 'I am full of energy and ready to take on the day.'",
  'Laugh for a Minute – Watch a funny video or recall a moment that made you laugh. Laughter is an instant energy boost.',
  'Visualize Success – Picture yourself achieving a goal today. Feel the energy of accomplishment and let it motivate you.',
  'Mindful Walk – Take a walk while focusing on each step, your breath, and the world around you. It’ll help clear your mind.',
  'Declutter Your Space – Tidying up your desk or environment can instantly boost your energy and help you feel more productive.',
  'Quick Dance Break – Put on your favorite upbeat song and dance for a few minutes. Movement releases endorphins!',
  'Eat a Healthy Snack – Choose a healthy snack like fruit or nuts to fuel your body and keep your energy levels up.',
  'Set a Mini Goal – Pick one small task to complete right now. Accomplishing it will give you a sense of momentum.',
  'Drink Herbal Tea – Take a moment to relax with a calming herbal tea like chamomile or peppermint.',
  "Say 'I Can' – Say out loud, 'I can do this!' It’s a quick confidence boost that helps shift your mindset.",
  'Step Away from Screens – Take a few minutes to unplug from screens and reconnect with yourself and your surroundings.',
  'Try a New Activity – Do something you’ve never tried before, even if it’s small, like trying a new recipe or hobby.',
  'Mindful Breathing – Breathe in for a count of 4, hold for 4, and exhale for 4. Repeat for a minute to refresh your mind.',
  'Stretch Your Neck & Shoulders – Gently stretch your neck and shoulders to release tension and boost energy.',
  "Positive Self-Talk – Replace negative thoughts with positive affirmations like, 'I’ve got this' or 'I am enough.'",
  'Give a Compliment – Compliment someone or yourself. It creates positive energy and lifts spirits.',
  'Visualize Your Dream Day – Close your eyes and imagine everything going perfectly today. Feel the excitement and energy it brings.',
  'Practice Gratitude for the Little Things – Take a moment to appreciate small pleasures, like your morning coffee or a moment of silence.',
  'Stretch Your Back – Stand tall and stretch your back to relieve stress and refresh your body.',
  'Enjoy Silence – Take a few minutes of complete silence to reset and re-energize your mind.',
  'Challenge Yourself – Push yourself to take on a small challenge. Whether it’s a tough task or trying something new, it builds confidence.',
  'Say No to Stress – Whenever stress creeps in, stop and take a deep breath. Let go of the tension and focus on calmness.',
  'Take a Power Nap – A 10-20 minute nap can re-energize you for the rest of the day.',
  'Go for a Quick Jog – Even a short burst of physical activity can boost energy and clear your mind.',
  'Enjoy a Moment of Stillness – Sit in silence for a few moments, focusing on your breath and the present moment.',
  'Celebrate Small Wins – Acknowledge any small achievement today and feel proud of your progress.',
  'Listen to Uplifting Music – Play a song that lifts your spirits and helps you feel energized.',
  'Breathe in Nature – Go outside and take a few deep breaths, soaking in the natural world to refresh your energy.',
  'Take a Break from Social Media – Unplug for a little while to recharge your energy and focus on real-life connections.',
  'Write a Quick To-Do List – Jot down your tasks for the day to clear your mind and set a productive tone.',
  'Find Your Happy Place – Close your eyes and picture a place that makes you feel peaceful and energized.',
  'Dance It Out – Move to your favorite song for a minute to shake off any stress and get your energy flowing.',
  'Appreciate Your Strength – Remind yourself of your resilience and strength. You’ve overcome challenges before, and you can do it again.',
  'Find Something Beautiful – Look for something beautiful around you, whether it’s a sunset, flower, or piece of art, and enjoy its beauty.',
  'Focus on Your Breathing – Take five deep breaths, in and out slowly, to bring your focus back to the present and relax.',
  'Do a Random Act of Kindness – Do something kind for someone else. It lifts your spirits and spreads positivity.',
  'Smile to Yourself – Smile in the mirror, even if just for a second. It boosts your mood and energy.',
  'Connect with a Friend – Reach out to someone you care about for a quick chat or message to recharge emotionally.',
  'Be Present – Stop multitasking for a moment and focus on what’s happening right now. It helps conserve mental energy.',
  'Say Thank You – Express gratitude to someone today, whether it’s for a small favor or just their support.',
  'Take a Nature Walk – A short walk in nature can help clear your mind and boost your energy levels.',
  'Practice Forgiveness – Release any negative emotions toward someone or yourself. Letting go will free up your energy.',
  'Connect with Your Inner Light – Take a quiet moment to close your eyes and visualize a bright light within you, growing stronger and filling you with energy.',
];
